seq_idxs_ids=[0];
error_type = 0;
config_plot_type = -1;

%---------------------------------------------------------------------%
% ------------------- Synthetic Dataset with SSMs ------------------- %
%---------------------------------------------------------------------%

actor_ids=[15];
plot_id = 1000;
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('SSM Synthetic  + Noise + RBF with FCLK/NCC - 2DOF');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C1_ncc50r30i4u_8_0', 1, 'rbf', 9, '0', '2', '8', 'blue', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C1_ncc50r30i4u_6_1', 1, 'rbf', 9, '0', '2', '6', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C1_ncc50r30i4u_4_1', 1, 'rbf', 9, '0', '2', '4', 'slate_gray', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C1_ncc50r30i4u_2_1', 1, 'rbf', 9, '0', '2', '2', 'cyan', '-'}),... 	
    };	
actor_ids=[15];
plot_id = 1001;
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('SSM Synthetic  + Noise + RBF with FCLK/NCC - 4DOF');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C1_ncc50r30i4u_8_0', 1, 'rbf', 9, '0', '4', '8', 'blue', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C1_ncc50r30i4u_6_1', 1, 'rbf', 9, '0', '4', '6', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C1_ncc50r30i4u_4_1', 1, 'rbf', 9, '0', '4', '4', 'slate_gray', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C1_ncc50r30i4u_2_1', 1, 'rbf', 9, '0', '4', '2', 'cyan', '-'}),... 	
    };	
actor_ids=[15];
plot_id = 1002;
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('SSM Synthetic  + Noise + RBF with FCLK/NCC - 6DOF');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C1_ncc50r30i4u_8_0', 1, 'rbf', 9, '0', '6', '8', 'blue', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C1_ncc50r30i4u_6_1', 1, 'rbf', 9, '0', '6', '6', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C1_ncc50r30i4u_4_1', 1, 'rbf', 9, '0', '6', '4', 'slate_gray', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C1_ncc50r30i4u_2_1', 1, 'rbf', 9, '0', '6', '2', 'cyan', '-'}),... 	
    };		
plot_id = 1321;
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('FCLK Synthetic + Noise + RBF');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C1_riu50r30i4u_8_0', 1, 'rbf', 9, '0', '', 'RIU', 'maroon', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C1_ngf50r30i4u_8_0', 1, 'rbf', 9, '0', '', 'NGF', 'gold', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C2_ccre16b50r30i4u_8_0', 1, 'rbf', 9, '0', '', 'CCRE', 'green', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C1_scv50r30i4u_8_0', 1, 'rbf', 9, '0', '', 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C1_rscv50r30i4u_8_0', 1, 'rbf', 9, '0', '', 'RSCV', 'magenta', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, '', 0,  1, 'fclmcw1C1_lscv50r30i4u_8_0', 1, 'rbf', 9, '0', '', 'LSCV', 'orange', '-'}),...
    };
	
%---------------------------------------------------------------------------------%
% ------------------- Comparing SSMs with various SMs and AMs ------------------- %
%---------------------------------------------------------------------------------%	

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%% learning trackers %%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

plot_id = 1;
actor_ids=[0, 1, 2];
plot_titles{3, plot_id}=sprintf('SSIM');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'kcf', 'ssd50r30i4u', '8', '2', 0, 'KCF', 'red', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'dsst', 'ssd50r30i4u', '8', '2', 0, 'DSST', 'green', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'iclkI1', 'ssim50r30i4u', '2', '2', 1, 'ICLK', 'forest_green', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'fclkC1', 'ssim50r30i4u', '2', '2', 1, 'FCLK', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'ssim50r30i4u', '2', '2', 1, 'ESM', 'magenta', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'ialkC1', 'ssim50r30i4u', '2', '2', 1, 'IALK', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'falkC1', 'ssim50r30i4u', '2', '2', 1, 'FALK', 'cyan', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'nnic1kI1', 'ssim50r30i4u', '2', '2', 1, 'NNIC', 'blue', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'nn1k', 'ssim50r30i4u', '2', '2', 1, 'NN1K', 'orange', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'nn10k', 'ssim50r30i4u', '2', '2', 1, 'NN10K', 'black', '-'}),...
    };	

	
plot_id = 2;
actor_ids=[0, 1, 2];
plot_titles{3, plot_id}=sprintf('SPSS');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'rct', 'ssd50r30i4u', '8', '2', 0, 'RCT', 'blue', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'tld', 'ssd50r30i4u', '8', '2', 0, 'TLD', 'green', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'cmt', 'ssd50r30i4u', '8', '2', 0, 'CMT', 'purple', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'iclkI1', 'spss50r30i4u', '2', '2', 1, 'ICLK', 'forest_green', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'fclkC1', 'spss50r30i4u', '2', '2', 1, 'FCLK', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'spss50r30i4u', '2', '2', 1, 'ESM', 'magenta', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'ialkC1', 'spss50r30i4u', '2', '2', 1, 'IALK', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'falkC1', 'spss50r30i4u', '2', '2', 1, 'FALK', 'cyan', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'nnic1kI1', 'spss50r30i4u', '2', '2', 1, 'NNIC', 'blue', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'nn1k', 'spss50r30i4u', '2', '2', 1, 'NN1K', 'orange', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'nn10k', 'spss50r30i4u', '2', '2', 1, 'NN10K', 'black', '-'}),...
    };	
	

% plot_id = 3;
% plot_titles{3, plot_id}=sprintf('Average Speeds');
% plot_data_descs{3, plot_id}={
    % containers.Map(bar_desc_keys, {-1, '', 89.36560116, 'DSST'}),...
    % containers.Map(bar_desc_keys, {-1, '', 90.05655582, 'KCF'}),...
    % containers.Map(bar_desc_keys, {-1, '', 9.926226446, 'TLD'}),...
    % containers.Map(bar_desc_keys, {-1, '', 36.97274304, 'RCT'}),...
    % containers.Map(bar_desc_keys, {-1, '', 38.35939266, 'CMT'}),...
    % containers.Map(bar_desc_keys, {-1, '', 683.3453707, 'ESM'}),...
    % containers.Map(bar_desc_keys, {-1, '', 809.0753726, 'FALK'}),...
    % containers.Map(bar_desc_keys, {-1, '', 819.9437984, 'FCLK'}),...
    % containers.Map(bar_desc_keys, {-1, '', 1678.204306, 'IALK'}),...
    % containers.Map(bar_desc_keys, {-1, '', 2502.01325, 'ICLK'}),...
    % containers.Map(bar_desc_keys, {-1, '', 106.5820543, 'NNIC'}),...
    % containers.Map(bar_desc_keys, {-1, '', 141.1899191, 'NN1K'}),...
    % containers.Map(bar_desc_keys, {-1, '', 19.27713401, 'NN10K'}),...
    % };
	

plot_id = 5;
actor_ids=[0,1, 2];
plot_titles{3, plot_id}=sprintf('SPSS');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'spss50r30i4u', '2', '2', 1, 'Translation', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'spss50r30i4u', '3', '3', 1, 'Isometry', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'spss50r30i4u', '4', '4', 1, 'Similitude', 'blue', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'spss50r30i4u', '6', '6', 1, 'Affine', 'cyan', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'spss50r30i4u', '8', '0', 0, 'SL3 Homography', 'purple', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'spss50r30i4u', '8', '0', 0, 'Corner Homography', 'orange', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'spss50r30i4u', '8', '0', 0, 'Homography', 'magenta', '-'}),...
    };
plot_id = 6;
actor_ids=[0, 1, 2];
plot_titles{3, plot_id}=sprintf('NCC');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'ncc50r30i4u', '2', '2', 1, 'Translation', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'ncc50r30i4u', '3', '3', 1, 'Isometry', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'ncc50r30i4u', '4', '4', 1, 'Similitude', 'blue', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'ncc50r30i4u', '6', '6', 1, 'Affine', 'cyan', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'ncc50r30i4u', '8', '0', 0, 'SL3 Homography', 'purple', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'ncc50r30i4u', '8', '0', 0, 'Corner Homography', 'orange', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'ncc50r30i4u', '8', '0', 0, 'Homography', 'magenta', '-'}),...
    };
	
plot_id = 7;
actor_ids=[0, 1, 2];
plot_titles{3, plot_id}=sprintf('FCLK');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'ssd50r30i4u', '2', '2', 1, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'rscv50r30i4u', '2', '2', 1, 'RSCV', 'purple', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'zncc50r30i4u', '2', '2', 1, 'ZNCC', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'ncc50r30i4u', '2', '2', 1, 'NCC', 'blue', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'ssim50r30i4u', '2', '2', 1, 'SSIM', 'red', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'esmDJSSH', 'spss50r30i4u', '2', '2', 1, 'SPSS', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'fclkC1', 'ssd50r30i4u', '2', '2', 1, '', 'forest_green', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'fclkC1', 'rscv50r30i4u', '2', '2', 1, '', 'purple', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'fclkC1', 'zncc50r30i4u', '2', '2', 1, '', 'cyan', '--'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'fclkC1', 'ncc50r30i4u', '2', '2', 1, '', 'blue', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'fclkC1', 'ssim50r30i4u', '2', '2', 1, '', 'red', '--'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  0, '', 'fclkC1', 'spss50r30i4u', '2', '2', 1, '', 'magenta', '--'}),... 
    };	
	
	
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%% Journal Experiments  %%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	
plot_id = 8;
actor_ids=[0];
error_type = 0;
config_plot_type=0
plot_titles{3, plot_id}=sprintf('Comparing RKL with Learning based Trackers using 4DOF GT');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'rklcv50r25pfc_ssd50r30i4u_4_0', '', '', '', '4', 0, 'RKLT', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'dsst4', '50r30i4u', '4', '4', 0, 'RSST', 'green', '-'}),...	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'dsst3', '50r30i4u', '4', '4', 0, 'DSST 3DOF', 'green', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'dsst2', '50r30i4u', '4', '4', 0, 'DSST 2DOF', 'green', ':'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'cmt4', '50r30i4u', '4', '4', 0, 'CMT 4DOF', 'cyan', '-'}),...  
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'cmt3', '50r30i4u', '4', '4', 0, 'CMT 3DOF', 'cyan', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'cmt2', '50r30i4u', '4', '4', 0, 'CMT 2DOF', 'cyan', ':'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'kcf', '50r30i4u', '4', '4', 0, 'KCF', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'rct', '50r30i4u', '4', '4', 0, 'RCT', 'black', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'strk', '50r30i4u', '4', '4', 0, 'Struck', 'purple', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'frg', '50r30i4u', '4', '4', 0, 'FragTrack', 'orange', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'tld', '50r30i4u', '4', '4', 0, 'TLD', 'magenta', '-'}),...
   containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'gtrn', '50r30i4u', '4', '4', 0, 'GOTURN', 'blue', '-'}),...
    };
	
plot_id = 80;
actor_ids=[0];
error_type = 0;
config_plot_type=1;
plot_titles{3, plot_id}=sprintf('Comparing RKL with Learning based Trackers using 4DOF GT');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'rklcv50r25pfc_ssd50r30i4u_4_0', '', '', '', '4', 0, 'RKLT', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'dsst4', '50r30i4u', '4', '4', 0, 'RSST', 'green', '-'}),...	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'dsst3', '50r30i4u', '4', '4', 0, 'DSST 3DOF', 'green', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'dsst2', '50r30i4u', '4', '4', 0, 'DSST 2DOF', 'green', ':'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'cmt4', '50r30i4u', '4', '4', 0, 'CMT 4DOF', 'cyan', '-'}),...  
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'cmt3', '50r30i4u', '4', '4', 0, 'CMT 3DOF', 'cyan', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'cmt2', '50r30i4u', '4', '4', 0, 'CMT 2DOF', 'cyan', ':'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'kcf', '50r30i4u', '4', '4', 0, 'KCF', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'rct', '50r30i4u', '4', '4', 0, 'RCT', 'black', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'strk', '50r30i4u', '4', '4', 0, 'Struck', 'purple', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'frg', '50r30i4u', '4', '4', 0, 'FragTrack', 'orange', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'tld', '50r30i4u', '4', '4', 0, 'TLD', 'magenta', '-'}),...
   containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'gtrn', '50r30i4u', '4', '4', 0, 'GOTURN', 'blue', '-'}),...
    };
	
plot_id = 81;
actor_ids=[12];
error_type = 0;
seq_idxs_ids=[10];
enable_subseq = 1;
config_plot_type = -1;
plot_titles{3, plot_id}=sprintf('Comparing RKL with Learning based Trackers');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, 'rklcv50r25pfc_ncc50r30i4u_4_0', '', '', '', '0', 0, 'RKLT/2K', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, 'rklcv50r10ki5pfc_ncc50r30i4u_4_0', '', '', '', '0', 0, 'RKLT/10K', 'red', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, 'gridcv50r10ki25p_ssd50r30i4u_4_0', '', '', '', '0', 0, 'Grid/10K', 'peach_puff', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'dsstr14', '50r30i4u', '4', '0', 0, 'RSST', 'green', '-'}),...	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'dsstr13', '50r30i4u', '4', '0', 0, 'DSST 3DOF', 'green', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'dsstr12', '50r30i4u', '4', '0', 0, 'DSST 2DOF', 'green', ':'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'cmt4', '50r30i4u', '4', '0', 0, 'CMT 4DOF', 'cyan', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'cmt3', '50r30i4u', '4', '0', 0, 'CMT 3DOF', 'cyan', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'cmt2', '50r30i4u', '4', '0', 0, 'CMT 2DOF', 'cyan', ':'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'kcf', '50r30i4u', '4', '0', 0, 'KCF', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'rct', '50r30i4u', '4', '0', 0, 'RCT', 'black', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'strk', '50r30i4u', '4', '0', 0, 'Struck', 'purple', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'frg', '50r30i4u', '4', '0', 0, 'FragTrack', 'orange', '-'}),...
     containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'tld', '50r30i4uNPP', '4', '0', 0, 'TLD', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'gtrn', '50r30i4u', '4', '0', 0, 'GOTURN', 'blue', '-'}),...
	% containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'mil', '50r30i4u', '4', '0', 0, 'MIL', 'black', '-'}),...
	};
plot_id = 82;
actor_ids=[12];
error_type = 0;
seq_idxs_ids=[10];
enable_subseq = 1;
config_plot_type = 1;
plot_titles{3, plot_id}=sprintf('Comparing RKL with Learning based Trackers');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, 'rklcv50r25pfc_ncc50r30i4u_4_0', '', '', '', '0', 0, 'RKLT', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'dsstr14', '50r30i4u', '4', '0', 0, 'RSST', 'green', '-'}),...	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'dsstr13', '50r30i4u', '4', '0', 0, 'DSST 3DOF', 'green', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'dsstr12', '50r30i4u', '4', '0', 0, 'DSST 2DOF', 'green', ':'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'cmt4', '50r30i4u', '4', '0', 0, 'CMT 4DOF', 'cyan', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'cmt3', '50r30i4u', '4', '0', 0, 'CMT 3DOF', 'cyan', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'cmt2', '50r30i4u', '4', '0', 0, 'CMT 2DOF', 'cyan', ':'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'kcf', '50r30i4u', '4', '0', 0, 'KCF', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'rct', '50r30i4u', '4', '0', 0, 'RCT', 'black', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'strk', '50r30i4u', '4', '0', 0, 'Struck', 'purple', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'frg', '50r30i4u', '4', '0', 0, 'FragTrack', 'orange', '-'}),...
     containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'tld', '50r30i4uNPP', '4', '0', 0, 'TLD', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'gtrn', '50r30i4u', '4', '0', 0, 'GOTURN', 'blue', '-'}),...
	%containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'mil', '50r30i4u', '4', '0', 0, 'MIL', 'black', '-'}),...
	};
config_plot_type=-1;

plot_id = 83;
actor_ids=[12];
error_type = 0;
seq_idxs_ids=[10];
enable_subseq = 1;
config_plot_type = -1;
plot_titles{3, plot_id}=sprintf('Comparing RKL with Learning based Trackers without PreProc');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, 'rklcv100r25pfc_ncc100r30i4u_4_0', '', '', '', '0', 0, 'RKLT 4DOF', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'dsst4', '50r30i4uNPP', '4', '0', 0, 'RSST', 'green', '-'}),...	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'dsst3', '50r30i4uNPP', '4', '0', 0, 'DSST 3DOF', 'green', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'dsst2', '50r30i4uNPP', '4', '0', 0, 'DSST 2DOF', 'green', ':'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'cmt4', '50r30i4uNPP', '4', '0', 0, 'CMT 4DOF', 'cyan', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'cmt3', '50r30i4uNPP', '4', '0', 0, 'CMT 3DOF', 'cyan', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'cmt2', '50r30i4uNPP', '4', '0', 0, 'CMT 2DOF', 'cyan', ':'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'kcf', '50r30i4uNPP', '4', '0', 0, 'KCF', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'rct', '50r30i4uNPP', '4', '0', 0, 'RCT', 'black', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'strk', '50r30i4uNPP', '4', '0', 0, 'Struck', 'purple', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'frg', '50r30i4uNPP', '4', '0', 0, 'FragTrack', 'orange', '-'}),...
     containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'tld', '50r30i4uNPP', '4', '0', 0, 'TLD', 'magenta', '-'}),...
	 containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'mil', '50r30i4uNPP', '4', '0', 0, 'MIL', 'black', '-'}),...
    %containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  enable_subseq, '', 'gtrn', '50r30i4uNPP', '4', '0', 0, 'GOTURN', 'blue', '-'}),...
	};

	
plot_id = 811;
actor_ids=[12];
error_type = 0;
seq_idxs_ids=[10];
plot_titles{3, plot_id}=sprintf('Comparing RKL with Learning based Trackers using SubSeq');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'gridcv100r25p_ssd50r30i4u_4_0', '', '', '', '0', 0, 'Grid4', 'peach_puff', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'gridcv100r25p_ssd50r30i4u_2_0', '', '', '', '0', 0, 'Grid2', 'black', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'kcf', '50r30i4u', '4', '0', 0, 'KCF', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'dsst2', '50r30i4u', '4', '0', 0, 'DSST2', 'green', ':'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'dsst3', '50r30i4u', '4', '0', 0, 'DSST3', 'green', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'dsst4', '50r30i4u', '4', '0', 0, 'RSST', 'green', '-'}),...	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'rct', '50r30i4u', '4', '0', 0, 'RCT', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'strk', '50r30i4u', '4', '0', 0, 'Struck', 'purple', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'tld', '50r30i4u', '4', '0', 0, 'TLD', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'cmt2', '50r30i4u', '4', '0', 0, 'CMT2', 'cyan', ':'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'cmt3', '50r30i4u', '4', '0', 0, 'CMT3', 'cyan', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'cmt4', '50r30i4u', '4', '0', 0, 'CMT4', 'cyan', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'frg', '50r30i4u', '4', '0', 0, 'FragTrack', 'orange', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'gtrn', '50r30i4u', '4', '0', 0, 'GOTURN', 'blue', '-'}),...
    };
seq_idxs_ids=[0];

plot_id = 84;
actor_ids=[8];
plot_titles{3, plot_id}=sprintf('Comparing Learning based Trackers with Jaccard Error');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 2,  0, '', 'kcf', '50r30i4u', '4', '0', 0, 'KCF', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 2,  0, '', 'dsst2', '50r30i4u', '4', '0', 0, 'DSST2', 'purple', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 2,  0, '', 'dsst3', '50r30i4u', '4', '0', 0, 'DSST3', 'cyan', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 2,  0, '', 'dsst4', '50r30i4u', '4', '0', 0, 'RSST', 'blue', '-'}),...	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 2,  0, '', 'rct', '50r30i4u', '4', '0', 0, 'RCT', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 2,  0, '', 'strk', '50r30i4u', '4', '0', 0, 'Struck', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 2,  0, '', 'tld', '50r30i4u', '4', '0', 0, 'TLD', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 2,  0, '', 'cmt2', '50r30i4u', '4', '0', 0, 'CMT2', 'orange', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 2,  0, '', 'cmt3', '50r30i4u', '4', '0', 0, 'CMT3', 'peach_puff', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 2,  0, '', 'cmt4', '50r30i4u', '4', '0', 0, 'CMT4', 'black', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 2,  0, '', 'frg', '50r30i4u', '4', '0', 0, 'FragTrack', 'light_slate_gray', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 2,  0, '', 'mil', '50r30i4u', '4', '0', 0, 'MIL', 'sky_blue', '-'}),...
    };
plot_id = 841;
actor_ids=[7];
plot_titles{3, plot_id}=sprintf('Comparing Learning based Trackers with Jaccard Error and SubSeq 10');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'kcf', '50r30i4u', '4', '0', 0, 'KCF', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'dsst2', '50r30i4u', '4', '0', 0, 'DSST2', 'purple', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'dsst3', '50r30i4u', '4', '0', 0, 'DSST3', 'cyan', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'dsst4', '50r30i4u', '4', '0', 0, 'RSST', 'blue', '-'}),...	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'rct', '50r30i4u', '4', '0', 0, 'RCT', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'strk', '50r30i4u', '4', '0', 0, 'Struck', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'tld', '50r30i4u', '4', '0', 0, 'TLD', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'cmt2', '50r30i4u', '4', '0', 0, 'CMT2', 'orange', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'cmt3', '50r30i4u', '4', '0', 0, 'CMT3', 'peach_puff', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'cmt4', '50r30i4u', '4', '0', 0, 'CMT4', 'black', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, '', 'frg', '50r30i4u', '4', '0', 0, 'FragTrack', 'light_slate_gray', '-'}),...
    };	

% plot_id = 85;
% plot_titles{3, plot_id}=sprintf('Average MCD Error for RKLT and RSST');
% plot_data_descs{3, plot_id}={
    % containers.Map(bar_desc_keys, {-1, '', [17.56, 0.82], 'Fish\_lure\_left'}),...
    % containers.Map(bar_desc_keys, {-1, '', [28.73, 1.02], 'Fish\_lure\_right'}),...
    % containers.Map(bar_desc_keys, {-1, '', [42.76, 1.21], 'Fish\_lure\_fast\_left'}),...
    % containers.Map(bar_desc_keys, {-1, '', [18.57, 83.79], 'Fish\_lure\_fast\_right'}),...
    % containers.Map(bar_desc_keys, {-1, '', [ 10.16, 36.73], 'Hexagon\_task\_left'}),...
    % containers.Map(bar_desc_keys, {-1, '', [9.72, 116.16], 'Hexagon\_task\_right'}),...
    % containers.Map(bar_desc_keys, {-1, '', [24.8, 10.88], 'Hexagon\_task\_fast\_left'}),...
    % containers.Map(bar_desc_keys, {-1, '', [62.86, 49.7], 'Hexagon\_task\_fast\_right'}),...
    % containers.Map(bar_desc_keys, {-1, '', [8.34, 11.78], 'Key\_task\_left'}),...
    % containers.Map(bar_desc_keys, {-1, '', [15.42, 14.7], 'Key\_task\_right'}),...
    % containers.Map(bar_desc_keys, {-1, '', [20.4, 22.13], 'Key\_task\_fast\_left'}),...
    % containers.Map(bar_desc_keys, {-1, '', [25.02, 35.24	], 'Key\_task\_fast\_right'}),...
    % };
	
plot_id = 851;
plot_titles{3, plot_id}=sprintf('Average MCD Error for RKLT and RSST');
plot_data_descs{3, plot_id}={
    containers.Map(bar_desc_keys, {-1, '', '', [17.56, 0.82, 28.73, 1.02, 42.76, 1.21, 18.57, 83.79], 'Fish\_lure', {'cyan', 'cyan', 'green', 'green', 'yellow', 'yellow', 'pink', 'pink'}, {'-', '--', '-', '--', '-', '--', '-', '--'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [ 10.16, 36.73, 9.72, 116.16, 24.8, 10.88, 62.86, 49.7], 'Hexagon\_task', {'cyan', 'cyan', 'green', 'green', 'yellow', 'yellow'}, {'-', '--', '-', '--', '-', '--'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [8.34, 11.78, 15.42, 14.7,20.4, 22.13,25.02, 35.24], 'Key\_task', {'cyan', 'cyan', 'green', 'green', 'yellow', 'yellow'}, {'-', '--', '-', '--', '-', '--'}}),...
    };
	
	
plot_id = 86;
actor_ids=[0, 1, 2, 3];
plot_titles{3, plot_id}=sprintf('LT1');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'cmt2_50r30i4u_2r_0', '', '', '', '2r', 0, 'CMT', 'red', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'dsst2_50r30i4u_2r_0', '', '', '', '2r', 0, 'DSST', 'green', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'frg_50r30i4u_2r_0', '', '', '', '2r', 0, 'FRG', 'forest_green', '--'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'kcfR2_50r30i4u_2r_0', '', '', '', '2r', 0, 'KCF', 'blue', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'faC1_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'FCLK', 'black', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'iccw1C1_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'ICLK', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'esmDJcw1C1_ssim50r30i4uReinitGT_2_0', '', '', '', '2', 0, 'ESM', 'peach_puff_3', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'faC1_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'FALK', 'cyan', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'iaC1_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'IALK', 'purple', '-'}),...	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'pf500d5s57s58s59s60s61car_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'PF', 'red', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'pffc500d5s57s58s59s60s61car_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'PFFC', 'green', '-'}),...
    };	
plot_id = 87;
actor_ids=[0, 1, 2, 3];
plot_titles{3, plot_id}=sprintf('LT2');
plot_data_descs{3, plot_id}={
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'rct_50r30i4u_2r_0', '', '', '', '2r', 0, 'RCT', 'purple', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'strk_50r30i4u_2r_0', '', '', '', '2r', 0, 'Struck', 'cyan', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'tld_50r30i4u_2r_0', '', '', '', '2r', 0, 'TLD', 'magenta', '--'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'gtrn_50r30i4u_2r_0', '', '', '', '2r', 0, 'GOTURN', 'black', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'nnkmn1k5d_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'NN', 'maroon', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'nnickmn1k5d_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'NNIC', 'gold', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'gridfc10rLMS25p10Ki5t_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'RANSAC', 'forest_green', '-'}),...	
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, error_type,  1, 'rklfc10rLMS25p10Ki5t_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'RKLT', 'blue', '-'}),...	
    };	

plot_id = 88;
plot_titles{3, plot_id}=sprintf('Average Speeds');
plot_data_descs{3, plot_id}={
    containers.Map(bar_desc_keys, {-1, '', '', 56.59, 'DSST',{'forest_green'},{'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', 56.52, 'KCF',{'forest_green'},{'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', 19.78, 'TLD',{'forest_green'},{'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', 83.53, 'RCT',{'forest_green'},{'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', 77.51, 'CMT',{'forest_green'},{'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', 25.73, 'FragTrack',{'forest_green'},{'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', 39.73, 'Struck',{'forest_green'},{'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', 48.97, 'GOTURN',{'forest_green'},{'-'}}),...	
	containers.Map(bar_desc_keys, {-1, '', '', 29.98, 'RKLT',{'forest_green'},{'-'}}),...
	containers.Map(bar_desc_keys, {-1, '', '', 36.79, 'RANSAC',{'forest_green'},{'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', 225.79, 'NNIC',{'forest_green'},{'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', 278.70, 'NN',{'forest_green'},{'-'}}),...
	containers.Map(bar_desc_keys, {-1, '', '', 56.70, 'PFFC',{'forest_green'},{'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', 61.61, 'PF',{'forest_green'},{'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', 2291.32, 'IALK',{'forest_green'},{'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', 1369.02, 'FALK',{'forest_green'},{'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', 1033.60, 'ESM',{'forest_green'},{'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', 3215.67, 'ICLK',{'forest_green'},{'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', 1395.04, 'FCLK',{'forest_green'},{'-'}}),...
   };
	
plot_id = 881;
plot_titles{3, plot_id}=sprintf('Average Speeds');
plot_data_descs{3, plot_id}={
    containers.Map(bar_desc_keys, {-1, '', '', [17.56, 0.82, 28.73, 1.02, 42.76, 1.21, 18.57, 83.79], 'Fish\_lure', {'cyan', 'cyan', 'green', 'green', 'yellow', 'yellow', 'pink', 'pink'}, {'-', '--', '-', '--', '-', '--', '-', '--'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [ 10.16, 36.73, 9.72, 116.16, 24.8, 10.88, 62.86, 49.7], 'Hexagon\_task', {'cyan', 'cyan', 'green', 'green', 'yellow', 'yellow'}, {'-', '--', '-', '--', '-', '--'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [8.34, 11.78, 15.42, 14.7,20.4, 22.13,25.02, 35.24], 'Key\_task', {'cyan', 'cyan', 'green', 'green', 'yellow', 'yellow'}, {'-', '--', '-', '--', '-', '--'}}),...
    };
	
	
plot_id = 89;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('RANSAC');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_ssim50r30i4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_spss50r30i4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_ncc50r30i4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_zncc50r30i4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_scv50r30i4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_rscv50r30i4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    };

plot_id = 90;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('RKLT');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_ssim50r30i4u_8_0', '', '', '', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_spss50r30i4u_8_0', '', '', '', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10r25p10Ki5t_ncc50r30i4u_8_0', '', '', '', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_ssd50r30i4u_8_0', '', '', '', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10r25p10Ki5t_zncc50r30i4u_8_0', '', '', '', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_scv50r30i4u_8_0', '', '', '', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_rscv50r30i4u_8_0', '', '', '', '0', 0, 'RSCV', 'magenta', '-'}),...
    };	

	
plot_id = 91;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('SSIM/ESM');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssim50r30i4uReinitGT_2_0', '', '', '', '2', 0, 'Translation', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssim50r30i4uReinitGT_3_0', '', '', '', '3', 0, 'Isometry', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssim50r30i4uReinitGT_4_0', '', '', '', '4', 0, 'Similitude', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssim50r30i4uReinitGT_6_0', '', '', '', '6', 0, 'Affine', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssim50r30i4u_8_0', '', '', '', '0', 0, 'Homography', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssim50r30i4u_l8_0', '', '', '', '0', 0, 'Lie Homography', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssim50r30i4u_c8_0', '', '', '', '0', 0, 'Corner Homography', 'magenta', '-'}),...
    };	
	
plot_id = 911;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('SSIM/FC');
plot_data_descs{3, plot_id}={	
   containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssim50r30i4uReinitGT_2_0', '', '', '', '2', 0, 'Translation', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssim50r30i4uReinitGT_3_0', '', '', '', '3', 0, 'Isometry', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssim50r30i4uReinitGT_4_0', '', '', '', '4', 0, 'Similitude', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssim50r30i4uReinitGT_6_0', '', '', '', '6', 0, 'Affine', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssim50r30i4u_8_0', '', '', '', '0', 0, 'Homography', 'green', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssim50r30i4u_c8_0', '', '', '', '0', 0, 'Corner Homography', 'magenta', '-'}),...
     containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssim50r30i4u_sl3_0', '', '', '', '0', 0, 'Lie Homography', 'purple', '-'}),...
    };	
	
plot_id = 912;
actor_ids=[0,1,2,3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('SSIM/RANSAC');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_ssim50r30i4uReinitGT_2_0', '', '', '', '2', 0, 'Translation', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_ssim50r30i4uReinitGT_3_0', '', '', '', '3', 0, 'Isometry', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_ssim50r30i4uReinitGT_4_0', '', '', '', '4', 0, 'Similitude', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_ssim50r30i4uReinitGT_6_0', '', '', '', '6', 0, 'Affine', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_ssim50r30i4u_8_0', '', '', '', '0', 0, 'Homography', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_ssim50r30i4u_8_0', '', '', '', '0', 0, 'Lie Homography', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_ssim50r30i4u_8_0', '', '', '', '0', 0, 'Corner Homography', 'magenta', '-'}),...
    };	
	
plot_id = 92;
plot_titles{3, plot_id}=sprintf('ViSP vs MTF Tracker Average Speed in FPS');
plot_data_descs{3, plot_id}={
    containers.Map(bar_desc_keys, {-1, '', '', [33.51, 599.64], 'ESM/SSD', {'red', 'blue'}, {'-', '-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [34.72, 650.05], 'ESM/ZNCC', {'red', 'blue'}, {'-', '-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [38.97, 546.53], 'FCLK/SSD', {'red', 'blue'}, {'-', '-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [32.44, 655.92], 'FCLK/ZNCC', {'red', 'blue'}, {'-', '-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [13.31, 52.23], 'FCLK/MI', {'red', 'blue'}, {'-', '-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [41.85, 1652.96], 'ICLK/SSD', {'red', 'blue'}, {'-', '-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [43.72, 1898.09], 'ICLK/ZNCC', {'red', 'blue'}, {'-', '-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [19.28, 308.17], 'ICLK/MI', {'red', 'blue'}, {'-', '-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [49.01, 548.61], 'FALK/SSD', {'red', 'blue'}, {'-', '-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [40.88, 650.14], 'FALK/ZNCC', {'red', 'blue'}, {'-', '-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [1.52, 46.83], 'FALK/MI', {'red', 'blue'}, {'-', '-'}}),...	
    };
	
plot_id = 921;
plot_titles{3, plot_id}=sprintf('Speed up provided by MTF');
plot_data_descs{3, plot_id}={
    containers.Map(bar_desc_keys, {-1, '', '', [17.89435989], 'ESM/SSD', {'purple'}, {'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [18.72263825], 'ESM/ZNCC', {'purple'}, {'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [14.02437773], 'FCLK/SSD', {'purple'}, {'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [18.41437395], 'FCLK/ZNCC', {'purple'}, {'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [3.924117205], 'FCLK/MI', {'purple'}, {'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [39.49725209], 'ICLK/SSD', {'purple'}, {'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [43.41468435], 'ICLK/ZNCC', {'purple'}, {'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [15.98392116], 'ICLK/MI', {'purple'}, {'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [11.19383799], 'FALK/SSD', {'purple'}, {'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [15.90362035], 'FALK/ZNCC', {'purple'}, {'-'}}),...
    containers.Map(bar_desc_keys, {-1, '', '', [30.80921053], 'FALK/MI', {'purple'}, {'-'}}),...	
    containers.Map(bar_desc_keys, {-1, '', '', [20.8893085], 'Average', {'purple'}, {'-'}}),...	
    };
	
	
plot_id = 93;
actor_ids=[0,1,2,3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('Different SMs with SSIM and 2r');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssim50r30i4u_2r_0', '', '', '', '2r', 0, 'ESM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC1_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'FA', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssim50r30i4u_2r_0', '', '', '', '2r', 0, 'FC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'IA', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'IC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k5d_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'NNIC', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k5d_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'NN', 'magenta', '-'}),...
    };	
	
plot_id = 931;
actor_ids=[0,1,2,3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('Different SMs with SSIM and 2r');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'GridFC', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s57s58s59s60s61car_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'PF', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s57s58s59s60s61car_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'PFFC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_ssim50r30i4uReinitGT_2r_0', '', '', '', '2r', 0, 'RKLFC', 'forest_green', '-'}),...
    };

	
	
