seq_idxs_ids=[0];
config_plot_type = -1;

config_plot_type=1;
plot_id = 191;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('FCLK');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssim50r30i4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_spss50r30i4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ncc50r30i4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C2_mi10b50r30i4u_8_0', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C2_ccre16b50r30i4u_8_0', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_zncc50r30i4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_scv50r30i4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_rscv50r30i4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_lscv50r30i4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),...
    };
config_plot_type = -1;
plot_id = 1911;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('FCLK');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssim50r30i4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_spss50r30i4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ncc50r30i4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C2_mi10b50r30i4u_8_0', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C2_ccre16b50r30i4u_8_0', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),...
    };
plot_id = 1912;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('FCLK');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_zncc50r30i4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_scv50r30i4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_rscv50r30i4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_lscv50r30i4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),...
    };
	
config_plot_type=1;
plot_id = 192;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('ICLK');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_ssim50r30i4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_spss50r30i4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_ncc50r30i4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C2_mi10b50r30i4u_8_0', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C2_ccre10b50r30i4u_8_0', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_zncc50r30i4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_scv50r30i4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_rscv50r30i4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_lscv50r30i4u_8_0', '', '', '8', '0', 0, 'ICLK', 'gold', '-'}),... 
    };
config_plot_type = -1;
plot_id = 1921;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('ICLK');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_ssim50r30i4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_spss50r30i4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_ncc50r30i4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C2_mi10b50r30i4u_8_0', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C2_ccre10b50r30i4u_8_0', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),... 
    };
plot_id = 1922;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('ICLK');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_zncc50r30i4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_scv50r30i4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_rscv50r30i4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_lscv50r30i4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };
	
config_plot_type=1;
plot_id = 193;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('ESM');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssim50r30i4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_spss50r30i4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ncc50r30i4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C2_mi10b50r30i4u_8_0', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C2_ccre16b50r30i4u_8_0', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_zncc50r30i4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_scv50r30i4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_rscv50r30i4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_lscv50r30i4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };	
config_plot_type = -1;
plot_id = 1931;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('ESM');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssim50r30i4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_spss50r30i4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ncc50r30i4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C2_mi10b50r30i4u_8_0', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C2_ccre16b50r30i4u_8_0', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),... 
    };	
plot_id = 1932;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('ESM');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_zncc50r30i4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_scv50r30i4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_rscv50r30i4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_lscv50r30i4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };	

config_plot_type=1;
plot_id = 194;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('FALK');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC1_ssim50r30i4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC1_spss50r30i4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC1_ncc50r30i4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC2_mi10b50r30i4u_8_0', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC2_ccre16b50r30i4u_8_0', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC1_zncc50r30i4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC1_scv50r30i4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC1_rscv50r30i4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC1_lscv50r30i4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };	
config_plot_type = -1;
plot_id = 1941;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('FALK');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC1_ssim50r30i4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC1_spss50r30i4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC1_ncc50r30i4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC2_mi10b50r30i4u_8_0', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC2_ccre16b50r30i4u_8_0', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),... 
    };	
plot_id = 1942;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('FALK');
plot_data_descs{3, plot_id}={	 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC1_zncc50r30i4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC1_scv50r30i4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC1_rscv50r30i4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'faC1_lscv50r30i4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };	

config_plot_type=1;
plot_id = 195;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('IALK');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_ssim50r30i4u_8_1', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_spss50r30i4u_8_1', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_ncc50r30i4u_8_1', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_mi10b50r30i4u_8_1', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_ccre16b50r30i4u_8_1', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_ssd50r30i4u_8_1', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_zncc50r30i4u_8_1', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_scv50r30i4u_8_1', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_rscv50r30i4u_8_1', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_lscv50r30i4u_8_1', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };	
config_plot_type = -1;
plot_id = 1951;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('IALK');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_ssim50r30i4u_8_1', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_spss50r30i4u_8_1', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_ncc50r30i4u_8_1', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_mi10b50r30i4u_8_1', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_ccre16b50r30i4u_8_1', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),...  
    };	
plot_id = 1952;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('IALK');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_ssd50r30i4u_8_1', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_zncc50r30i4u_8_1', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_scv50r30i4u_8_1', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_rscv50r30i4u_8_1', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iaC1_lscv50r30i4u_8_1', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };	
	
config_plot_type=1;
plot_id = 196;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('PF');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_ssim50r30i50a4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_spss50r30i1a4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_ncc50r30i50a4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_mi12b50r30i2a4u_8_0', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_ccre16b50r30i100a1bt4u_8_0', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_ssd50r30i5a4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_zncc50r30i50a4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_scv64b50r30i5a4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_rscv64b50r30i5a4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_lscv64b50r30i5a4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };	
config_plot_type = -1;
plot_id = 1961;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('PF');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_ssim50r30i50a4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_spss50r30i1a4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_ncc50r30i50a4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_mi12b50r30i2a4u_8_0', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_ccre16b50r30i100a1bt4u_8_0', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),... 
    };	
plot_id = 1962;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('PF');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_ssd50r30i5a4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_zncc50r30i50a4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_scv64b50r30i5a4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_rscv64b50r30i5a4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pf500d5s0s1s2s3s4car_lscv64b50r30i5a4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };		
	
config_plot_type=1;
plot_id = 197;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('PFFC');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_ssim50r30i50a4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_spss50r30i1a4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_ncc50r30i50a4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_mi12b50r30i2a4u_8_0', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_ccre16b50r30i100a1bt4u_8_0', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_ssd50r30i5a4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_zncc50r30i50a4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_scv64b50r30i5a4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_rscv64b50r30i5a4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_lscv64b50r30i5a4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };	
config_plot_type = -1;
plot_id = 1971;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('PFFC');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_ssim50r30i50a4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_spss50r30i1a4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_ncc50r30i50a4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_mi12b50r30i2a4u_8_0', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_ccre16b50r30i100a1bt4u_8_0', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),...
    };	
plot_id = 1972;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('PFFC');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_ssd50r30i5a4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_zncc50r30i50a4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_scv64b50r30i5a4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_rscv64b50r30i5a4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'pffc500d5s0s1s2s3s4car_lscv64b50r30i5a4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };	

	
config_plot_type=1;
plot_id = 198;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('NN');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_ssim50r1i4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_spss50r1i4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_ncc50r1i4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_mi24b50r30i4u_8_0', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_ccre24b50r1i4u_8_0', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_ssd50r1i4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_zncc50r1i4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_scv64bTrue50r1i4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_rscv64bTrue50r1i4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_lscvTrue64b50r1i4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };	
config_plot_type = -1;
plot_id = 1981;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('NN');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_ssim50r1i4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_spss50r1i4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_ncc50r1i4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_mi24b50r30i4u_8_0', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_ccre24b50r1i4u_8_0', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),... 
    };	
plot_id = 1982;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('NN');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_ssd50r1i4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_zncc50r1i4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_scv64bTrue50r1i4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_rscv64bTrue50r1i4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnkmn1k2s_lscvTrue64b50r1i4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };		
	
config_plot_type=1;
plot_id = 199;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('NNIC');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_ssim50r1i4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_spss50r1i4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_ncc50r1i4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_mi12b50r30i4u_8_0', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_ccre12b50r1i4u_8_0', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_ssd50r1i4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_zncc50r1i4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_scv64bTrue50r1i4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_rscv64bTrue50r1i4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_lscvTrue64b50r1i4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };		
config_plot_type = -1;
plot_id = 1991;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('NNIC');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_ssim50r1i4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_spss50r1i4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_ncc50r1i4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_mi12b50r30i4u_8_0', '', '', '8', '0', 0, 'MI', 'black', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_ccre12b50r1i4u_8_0', '', '', '8', '0', 0, 'CCRE', 'peach_puff_3', '-'}),... 
    };
plot_id = 1992;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('NNIC');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_ssd50r1i4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_zncc50r1i4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_scv64bTrue50r1i4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_rscv64bTrue50r1i4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'nnickmn1k2s_lscvTrue64b50r1i4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };	
	
config_plot_type=1;
plot_id = 200;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('RANSAC');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_ssim50r30i4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_spss50r30i4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc5rLMS50p10Ki5t_ncc50r30i4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc5rLMS50p10Ki5t_zncc50r30i4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_scv50r30i4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_rscv50r30i4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_lscv50r30i4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };
config_plot_type = -1;
plot_id = 2001;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('RANSAC');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_ssim50r30i4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_spss50r30i4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_ncc50r30i4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    };	
plot_id = 2002;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('RANSAC');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_zncc50r30i4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_scv50r30i4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_rscv50r30i4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'gridfc10rLMS25p10Ki5t_lscv50r30i4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };
	
	
config_plot_type = 1;
plot_id = 201;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('RKLT');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_ssim50r30i4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_spss50r30i4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10r25p10Ki5t_ncc50r30i4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10r25p10Ki5t_zncc50r30i4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_scv50r30i4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_rscv50r30i4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_lscv50r30i4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };	
config_plot_type = -1;
plot_id = 2011;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('RKLT');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_ssim50r30i4u_8_0', '', '', '8', '0', 0, 'SSIM', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_spss50r30i4u_8_0', '', '', '8', '0', 0, 'SPSS', 'cyan', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10r25p10Ki5t_ncc50r30i4u_8_0', '', '', '8', '0', 0, 'NCC', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'SSD', 'forest_green', '-'}),...
    };	
plot_id = 2012;
actor_ids=[0, 1, 2, 3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('RKLT');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10r25p10Ki5t_zncc50r30i4u_8_0', '', '', '8', '0', 0, 'ZNCC', 'green', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_scv50r30i4u_8_0', '', '', '8', '0', 0, 'SCV', 'purple', '-'}),...
	containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_rscv50r30i4u_8_0', '', '', '8', '0', 0, 'RSCV', 'magenta', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'rklfc10rLMS25p10Ki5t_lscv50r30i4u_8_0', '', '', '8', '0', 0, 'LSCV', 'gold', '-'}),... 
    };	
	
	
plot_id = 202;
actor_ids=[0,1,2,3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('PGB');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssdpgb50r30i4u_8_0', '', '', '8', '0', 0, 'ESM/PGB', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'ESM/SSD', 'red', '--'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssdpgb50r30i4u_8_0', '', '', '8', '0', 0, 'FC/PGB', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'FC/SSD', 'blue', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_ssdpgb50r30i4u_8_0', '', '', '8', '0', 0, 'IC/PGB', 'forest_green', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'IC/SSD', 'forest_green', '--'}),...
    };	
config_plot_type = 1;
plot_id = 2021;
actor_ids=[0,1,2,3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('PGB');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssdpgb50r30i4u_8_0', '', '', '8', '0', 0, 'ESM/PGB', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'ESM/SSD', 'red', '--'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssdpgb50r30i4u_8_0', '', '', '8', '0', 0, 'FC/PGB', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'FC/SSD', 'blue', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_ssdpgb50r30i4u_8_0', '', '', '8', '0', 0, 'IC/PGB', 'forest_green', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'IC/SSD', 'forest_green', '--'}),...
    };
config_plot_type = -1;

plot_id = 203;
actor_ids=[0,1,2,3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('GB');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssdgb50r30i4u_8_0', '', '', '8', '0', 0, 'ESM/PGB', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'ESM/SSD', 'red', '--'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssdgb50r30i4u_8_0', '', '', '8', '0', 0, 'FC/PGB', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'FC/SSD', 'blue', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_ssdgb50r30i4u_8_0', '', '', '8', '0', 0, 'IC/PGB', 'forest_green', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'IC/SSD', 'forest_green', '--'}),...
    };	
config_plot_type = 1;
plot_id = 2031;
actor_ids=[0,1,2,3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('GB');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssdgb50r30i4u_8_0', '', '', '8', '0', 0, 'ESM/PGB', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'ESM/SSD', 'red', '--'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssdgb50r30i4u_8_0', '', '', '8', '0', 0, 'FC/PGB', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'FC/SSD', 'blue', '--'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_ssdgb50r30i4u_8_0', '', '', '8', '0', 0, 'IC/PGB', 'forest_green', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_ssd50r30i4u_8_0', '', '', '8', '0', 0, 'IC/SSD', 'forest_green', '--'}),...
    };
config_plot_type = -1;

plot_id = 2032;
actor_ids=[0,1,2,3];
seq_idxs_ids=[0];
plot_titles{3, plot_id}=sprintf('GB');
plot_data_descs{3, plot_id}={	
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'esmDJcw1C1_ssdgb50r30i4u_8_0', '', '', '8', '0', 0, 'ESM/PGB', 'red', '-'}),...
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'fccw1C1_ssdgb50r30i4u_8_0', '', '', '8', '0', 0, 'FC/PGB', 'blue', '-'}),... 
    containers.Map(desc_keys, {actor_ids, seq_idxs_ids, config_plot_type, 0,  1, 'iccw1C1_ssdgb50r30i4u_8_0', '', '', '8', '0', 0, 'IC/PGB', 'forest_green', '-'}),... 
    };