clear all;
colRGBDefs;
colors = {
    'blue',...
    'cyan',...
    'maroon',...
    'gold',...
    'red',...
    'black',...
    'peach_puff_3',...
    'forest_green',...
    'green',...
    'purple',...
    'magenta',...
    'light_sky_blue',...
    };
y_data_base = 1 : plot_res;
x_data = 1 : plot_res;
plot_res = 100;
n_cols = length(colors);
y_data=zeros(n_cols, plot_res);
for col_id = 1:n_cols
    col=col_rgb{strcmp(col_names,colors{bar_id})};
    y_data(col_id, :) = y_data_base;
    plot()
end