#!/bin/bash

python3 "/mnt/c/UofA/MSc/Code/PTF/scpWithLogging.py" info_file="dgPolWm53WNOJ8PEioAL" auth_file="~/.ssh/id_rsa" key_root="/mnt/z" key_dir="UofA/admin" scp_path="/home/abhineet/" mode=-1 scp_name=mj2

