personViewer mesh/person-small0.obj motion/dancing1.bvh attach/W-small0.att 
personViewer  meshout.obj skeletonout.bvh attachout.att
personViewer mesh/person-small0.obj motion/dancing2.bvh attach/W-small0.att 
personViewer mesh/person-small0.obj motion/dancing3.bvh attach/W-small0.att 
personViewer mesh/person-small0.obj motion/dancing4.bvh attach/W-small0.att 
personViewer mesh/person-small0.obj motion/gymnastics1.bvh attach/W-small0.att 
personViewer mesh/person-small0.obj motion/gymnastics2.bvh attach/W-small0.att 
personViewer mesh/person-small0.obj motion/gymnastics3.bvh attach/W-small0.att 
personViewer  meshout.obj skeletonout.bvh attachout.att
personViewer mesh/person-small0.obj motion/hopscotch.bvh attach/W-small0.att 
personViewer mesh/person-small0.obj motion/punching.bvh attach/W-small0.att 
personViewer mesh/person-small0.obj motion/rundive.bvh attach/W-small0.att 
personViewer mesh/person-small0.obj motion/running.bvh attach/W-small0.att 
personViewer mesh/person-small0.obj motion/skeleton.bvh attach/W-small0.att 
